from flask import Blueprint

# One admin blueprint for the whole admin area
admin_bp = Blueprint("admin_bp", __name__, url_prefix="/admin")

# import modules so their @admin_bp.route decorators register
from . import core                          # /admin/
from .reading import routes as _reading     # /admin/reading/...
from .billing import routes as _billing     # /admin/billing/...
from .home import routes as _home     # /admin/home/...
from .loss import routes as _loss     # /admin/loss/...
