"""add patient profile

Revision ID: 19788357b9a5
Revises: 8c6a21489a8c
Create Date: 2026-08-03 12:00:33.787220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19788357b9a5'
down_revision: Union[str, Sequence[str], None] = '8c6a21489a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('id_number', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('medical_aid', sa.String(length=150), nullable=True),
    sa.Column('medical_aid_plan', sa.String(length=150), nullable=True),
    sa.Column('medical_aid_no', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['crm_practice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_enquiry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_crm_enquiry_patient_id', 'crm_patient', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_enquiry', schema=None) as batch_op:
        batch_op.drop_constraint('fk_crm_enquiry_patient_id', type_='foreignkey')
        batch_op.drop_column('patient_id')

    op.drop_table('crm_patient')
    # ### end Alembic commands ###
