"""Add BilExtractionLog

Revision ID: 45629455c046
Revises: 58742438723a
Create Date: 2026-06-30 13:43:35.787156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45629455c046'
down_revision: Union[str, Sequence[str], None] = '58742438723a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bil_extraction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('metro_account_no', sa.String(length=100), nullable=True),
    sa.Column('muni_email', sa.String(length=255), nullable=True),
    sa.Column('has_rates', sa.Boolean(), nullable=True),
    sa.Column('rates_amount', sa.Float(), nullable=True),
    sa.Column('amount_due', sa.Float(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bil_extraction_log')
    # ### end Alembic commands ###
