"""Add enrollment_id to BilProperty

Revision ID: 58742438723a
Revises: e4991ea413ee
Create Date: 2026-06-30 13:28:46.950258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58742438723a'
down_revision: Union[str, Sequence[str], None] = 'e4991ea413ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bil_property', sa.Column('enrollment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bil_property', 'user_enrollment', ['enrollment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bil_property', type_='foreignkey')
    op.drop_column('bil_property', 'enrollment_id')
    # ### end Alembic commands ###
