"""Add isolated UIP recorded Finance; frozen PostgreSQL DDL, no existing-table changes."""
from alembic import op
import sqlalchemy as sa
revision = "uip_p10_finance"
down_revision = "uip_p49_operations"
branch_labels = None
depends_on = None

DDL = (
    '\nCREATE TABLE uip_finance_commitment (\n\tid SERIAL NOT NULL, \n\torganization_id INTEGER NOT NULL, \n\treference VARCHAR(50) NOT NULL, \n\ttransaction_date DATE NOT NULL, \n\tamount NUMERIC(16, 2) NOT NULL, \n\tcategory VARCHAR(100) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tpublic_description TEXT NOT NULL, \n\tpublic_party VARCHAR(255) NOT NULL, \n\tprovider_id INTEGER, \n\twork_order_id INTEGER, \n\tgovernance_decision_id INTEGER, \n\tdocument_id INTEGER, \n\tmember_visible BOOLEAN NOT NULL, \n\tstatus VARCHAR(20) NOT NULL, \n\tversion INTEGER NOT NULL, \n\trecorded_by INTEGER NOT NULL, \n\trecorded_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\trequest_key VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT fk_uip_fc_provider_id FOREIGN KEY(provider_id, organization_id) REFERENCES uip_provider (id, organization_id), \n\tCONSTRAINT fk_uip_fc_work_order_id FOREIGN KEY(work_order_id, organization_id) REFERENCES uip_work_order (id, organization_id), \n\tCONSTRAINT fk_uip_fc_governance_decision_id FOREIGN KEY(governance_decision_id, organization_id) REFERENCES uip_resolution (id, organization_id), \n\tCONSTRAINT fk_uip_fc_document_id FOREIGN KEY(document_id, organization_id) REFERENCES uip_document (id, organization_id), \n\tCONSTRAINT uq_uip_fc_org UNIQUE (id, organization_id), \n\tCONSTRAINT uq_uip_fc_request UNIQUE (organization_id, request_key), \n\tCONSTRAINT ck_uip_fc_amount CHECK (amount > 0 AND version > 0), \n\tCONSTRAINT ck_uip_fc_status CHECK (status IN (\'OPEN\',\'PARTIALLY_PAID\',\'PAID\',\'CANCELLED\')), \n\tFOREIGN KEY(organization_id) REFERENCES core_organization (id), \n\tUNIQUE (reference), \n\tFOREIGN KEY(recorded_by) REFERENCES "user" (id)\n)\n\n',
    'CREATE INDEX ix_uip_fc_org_date ON uip_finance_commitment (organization_id, transaction_date)',
    '\nCREATE TABLE uip_finance_transaction (\n\tid SERIAL NOT NULL, \n\torganization_id INTEGER NOT NULL, \n\treference VARCHAR(50) NOT NULL, \n\ttransaction_date DATE NOT NULL, \n\tkind VARCHAR(20) NOT NULL, \n\tamount NUMERIC(16, 2) NOT NULL, \n\tcategory VARCHAR(100) NOT NULL, \n\tdescription TEXT NOT NULL, \n\tparty VARCHAR(255) NOT NULL, \n\tpublic_description TEXT NOT NULL, \n\tpublic_party VARCHAR(255) NOT NULL, \n\tprovider_id INTEGER, \n\twork_order_id INTEGER, \n\tgovernance_decision_id INTEGER, \n\tdocument_id INTEGER, \n\tcommitment_id INTEGER, \n\treversal_of_id INTEGER, \n\tcorrection_of_id INTEGER, \n\tcorrection_reason TEXT, \n\tstatus VARCHAR(20) NOT NULL, \n\tmember_visible BOOLEAN NOT NULL, \n\tversion INTEGER NOT NULL, \n\trecorded_by INTEGER NOT NULL, \n\trecorded_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\trequest_key VARCHAR(36) NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT fk_uip_ft_provider_id FOREIGN KEY(provider_id, organization_id) REFERENCES uip_provider (id, organization_id), \n\tCONSTRAINT fk_uip_ft_work_order_id FOREIGN KEY(work_order_id, organization_id) REFERENCES uip_work_order (id, organization_id), \n\tCONSTRAINT fk_uip_ft_governance_decision_id FOREIGN KEY(governance_decision_id, organization_id) REFERENCES uip_resolution (id, organization_id), \n\tCONSTRAINT fk_uip_ft_document_id FOREIGN KEY(document_id, organization_id) REFERENCES uip_document (id, organization_id), \n\tCONSTRAINT uq_uip_ft_org UNIQUE (id, organization_id), \n\tCONSTRAINT uq_uip_ft_request UNIQUE (organization_id, request_key), \n\tCONSTRAINT fk_uip_ft_commitment FOREIGN KEY(commitment_id, organization_id) REFERENCES uip_finance_commitment (id, organization_id), \n\tCONSTRAINT fk_uip_ft_reversal FOREIGN KEY(reversal_of_id, organization_id) REFERENCES uip_finance_transaction (id, organization_id), \n\tCONSTRAINT fk_uip_ft_correction FOREIGN KEY(correction_of_id, organization_id) REFERENCES uip_finance_transaction (id, organization_id), \n\tCONSTRAINT ck_uip_ft_kind CHECK (kind IN (\'INCOME\',\'EXPENDITURE\',\'ADJUSTMENT\')), \n\tCONSTRAINT ck_uip_ft_amount CHECK (amount <> 0 AND version > 0), \n\tCONSTRAINT ck_uip_ft_status CHECK ((status = \'POSTED\' AND reversal_of_id IS NULL AND (amount > 0 OR kind = \'ADJUSTMENT\')) OR (status = \'REVERSAL\' AND reversal_of_id IS NOT NULL)), \n\tCONSTRAINT ck_uip_ft_commitment CHECK (commitment_id IS NULL OR kind = \'EXPENDITURE\'), \n\tFOREIGN KEY(organization_id) REFERENCES core_organization (id), \n\tUNIQUE (reference), \n\tUNIQUE (reversal_of_id), \n\tUNIQUE (correction_of_id), \n\tFOREIGN KEY(recorded_by) REFERENCES "user" (id)\n)\n\n',
    'CREATE INDEX ix_uip_ft_org_date ON uip_finance_transaction (organization_id, transaction_date)',
    '\nCREATE TABLE uip_finance_budget_line (\n\tid SERIAL NOT NULL, \n\torganization_id INTEGER NOT NULL, \n\tyear_start DATE NOT NULL, \n\tcategory VARCHAR(100) NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_uip_fb_org UNIQUE (id, organization_id), \n\tCONSTRAINT uq_uip_fb_category UNIQUE (organization_id, year_start, category), \n\tCONSTRAINT ck_uip_fb_march CHECK (EXTRACT(MONTH FROM year_start) = 3 AND EXTRACT(DAY FROM year_start) = 1), \n\tFOREIGN KEY(organization_id) REFERENCES core_organization (id)\n)\n\n',
    '\nCREATE TABLE uip_finance_budget_revision (\n\tid SERIAL NOT NULL, \n\torganization_id INTEGER NOT NULL, \n\tbudget_line_id INTEGER NOT NULL, \n\trevision INTEGER NOT NULL, \n\tapproved_amount NUMERIC(16, 2) NOT NULL, \n\tdescription TEXT NOT NULL, \n\trevised_date DATE NOT NULL, \n\tgovernance_decision_id INTEGER, \n\trecorded_by INTEGER NOT NULL, \n\trecorded_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT fk_uip_fbr_line FOREIGN KEY(budget_line_id, organization_id) REFERENCES uip_finance_budget_line (id, organization_id), \n\tCONSTRAINT fk_uip_fbr_decision FOREIGN KEY(governance_decision_id, organization_id) REFERENCES uip_resolution (id, organization_id), \n\tCONSTRAINT uq_uip_fbr_revision UNIQUE (budget_line_id, revision), \n\tCONSTRAINT ck_uip_fbr_amount CHECK (approved_amount >= 0 AND revision > 0), \n\tFOREIGN KEY(organization_id) REFERENCES core_organization (id), \n\tFOREIGN KEY(recorded_by) REFERENCES "user" (id)\n)\n\n',
    '\nCREATE TABLE uip_finance_commitment_revision (\n\tid SERIAL NOT NULL, \n\torganization_id INTEGER NOT NULL, \n\tcommitment_id INTEGER NOT NULL, \n\trevision INTEGER NOT NULL, \n\tamount NUMERIC(16, 2) NOT NULL, \n\tcancelled BOOLEAN NOT NULL, \n\teffective_date DATE NOT NULL, \n\treason TEXT NOT NULL, \n\trecorded_by INTEGER NOT NULL, \n\trecorded_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT fk_uip_fcr_commitment FOREIGN KEY(commitment_id, organization_id) REFERENCES uip_finance_commitment (id, organization_id), \n\tCONSTRAINT uq_uip_fcr_revision UNIQUE (commitment_id, revision), \n\tCONSTRAINT ck_uip_fcr_amount CHECK (amount > 0 AND revision > 0), \n\tFOREIGN KEY(organization_id) REFERENCES core_organization (id), \n\tFOREIGN KEY(recorded_by) REFERENCES "user" (id)\n)\n\n',
    "CREATE FUNCTION uip_p10_immutable() RETURNS trigger LANGUAGE plpgsql AS $$\nBEGIN\n  RAISE EXCEPTION 'UIP financial history cannot be changed or deleted';\nEND $$",
    "CREATE FUNCTION uip_p10_transaction_guard() RETURNS trigger LANGUAGE plpgsql AS $$\nDECLARE original uip_finance_transaction%ROWTYPE;\nBEGIN\n  IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Posted financial history cannot be deleted'; END IF;\n  IF TG_OP = 'UPDATE' THEN\n    IF (to_jsonb(NEW) - 'member_visible' - 'version') IS DISTINCT FROM (to_jsonb(OLD) - 'member_visible' - 'version') THEN\n      RAISE EXCEPTION 'Use a reversal to correct posted financial history';\n    END IF;\n    RETURN NEW;\n  END IF;\n  IF NEW.reversal_of_id IS NOT NULL THEN\n    SELECT * INTO original FROM uip_finance_transaction WHERE id = NEW.reversal_of_id AND organization_id = NEW.organization_id FOR UPDATE;\n    IF NOT FOUND OR original.status <> 'POSTED' OR NEW.amount <> -original.amount OR NEW.kind <> original.kind OR NEW.transaction_date < original.transaction_date\n      OR ROW(NEW.category,NEW.commitment_id,NEW.provider_id,NEW.work_order_id,NEW.governance_decision_id,NEW.document_id,NEW.member_visible)\n         IS DISTINCT FROM ROW(original.category,original.commitment_id,original.provider_id,original.work_order_id,original.governance_decision_id,original.document_id,original.member_visible) THEN\n      RAISE EXCEPTION 'Invalid financial reversal';\n    END IF;\n  END IF;\n  RETURN NEW;\nEND $$",
    'CREATE TRIGGER uip_ft_guard BEFORE INSERT OR UPDATE OR DELETE ON uip_finance_transaction FOR EACH ROW EXECUTE FUNCTION uip_p10_transaction_guard()',
    'CREATE TRIGGER uip_fc_no_delete BEFORE DELETE ON uip_finance_commitment FOR EACH ROW EXECUTE FUNCTION uip_p10_immutable()',
    'CREATE TRIGGER uip_finance_budget_line_immutable BEFORE UPDATE OR DELETE ON uip_finance_budget_line FOR EACH ROW EXECUTE FUNCTION uip_p10_immutable()',
    'CREATE TRIGGER uip_finance_budget_revision_immutable BEFORE UPDATE OR DELETE ON uip_finance_budget_revision FOR EACH ROW EXECUTE FUNCTION uip_p10_immutable()',
    'CREATE TRIGGER uip_finance_commitment_revision_immutable BEFORE UPDATE OR DELETE ON uip_finance_commitment_revision FOR EACH ROW EXECUTE FUNCTION uip_p10_immutable()',
)


def upgrade():
    if op.get_bind().dialect.name != "postgresql":
        raise RuntimeError("UIP Finance requires PostgreSQL")
    for statement in DDL:
        op.execute(sa.text(statement))


def downgrade():
    raise RuntimeError("UIP financial history must be preserved; downgrade is refused")
