with open('C:\\Users\\Sanjith\\.gemini\\antigravity\\brain\\dcc17788-dfc9-47cd-bf94-3729fb287db0\\task.md', 'a', encoding='utf-8') as f:
    f.write("\n\n# MASTER BUILD ORDER (V1)\n")
    f.write("*As defined by the Blueprint. This overrides earlier granular milestones for tracking execution.*\n\n")
    f.write("## Foundation\n")
    f.write("- [ ] 1. Migration cleanup\n")
    f.write("- [ ] 2. Core organisation\n")
    f.write("- [ ] 3. Membership\n")
    f.write("- [ ] 4. Role/permission engine\n")
    f.write("- [ ] 5. Organisation context\n\n")
    f.write("## Operations\n")
    f.write("- [ ] 6. Interaction engine\n")
    f.write("- [ ] 7. Task engine\n")
    f.write("- [ ] 8. Reception dashboard\n")
    f.write("- [ ] 9. Manager dashboard\n\n")
    f.write("## Commercial\n")
    f.write("- [ ] 10. Credit ledger\n")
    f.write("- [ ] 11. Usage metering\n")
    f.write("- [ ] 12. AI Gateway\n\n")
    f.write("## Extended UIP\n")
    f.write("- [ ] 13. Providers\n")
    f.write("- [ ] 14. Municipality\n")
    f.write("- [ ] 15. Governance\n")
    f.write("- [ ] 16. Documents\n")
    f.write("- [ ] 17. Communications\n\n")
    f.write("## Intelligence & Production\n")
    f.write("- [ ] 18. Luna capabilities & Reporting\n")
    f.write("- [ ] 19. Security hardening\n")
    f.write("- [ ] 20. Manor Gardens Pilot & Rollout\n")
